# Generated by Django 5.1.7 on 2025-04-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productitem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='stock',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
