# Generated by Django 5.1.5 on 2025-02-17 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brand', '0004_remove_brand_description'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=500, null=True, verbose_name='Product Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('photo_url', models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='Product Image')),
                ('product_details', models.JSONField(blank=True, null=True, verbose_name='Product Details')),
                ('new_arrival', models.BooleanField(default=False, verbose_name='New Arrival')),
                ('our_product', models.BooleanField(default=False, verbose_name='Our Product')),
                ('activatedstatus', models.BooleanField(default=True, verbose_name='Activated Status')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brand.brand', verbose_name='Brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.category', verbose_name='Category')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.subcategory', verbose_name='Subcategory')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
