# Generated by Django 5.1.7 on 2025-04-10 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='online_special',
            field=models.BooleanField(default=False),
        ),
    ]
