# Generated by Django 5.1.5 on 2025-03-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='item_description',
            field=models.TextField(default='No description available'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='manufacturer_code',
            field=models.CharField(default='UNKNOWN', max_length=300),
        ),
    ]
