# Generated by Django 5.1.7 on 2025-04-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_picture',
            field=models.ImageField(blank=True, default='img/default-user.jpg', upload_to='profile_pics/'),
        ),
    ]
