# Generated by Django 5.1.5 on 2025-03-11 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='address_line',
            field=models.CharField(default='Default Address', max_length=255),
        ),
        migrations.AddField(
            model_name='account',
            name='city',
            field=models.CharField(default='Washington', max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='company_name',
            field=models.CharField(default='ABC', max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='country',
            field=models.CharField(default='United States', max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='fax_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='postal_code',
            field=models.CharField(default='000000', max_length=6),
        ),
        migrations.AddField(
            model_name='account',
            name='state',
            field=models.CharField(default='IL', max_length=100),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
