# Generated by Django 5.1.7 on 2025-03-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('zipcode', models.CharField(max_length=20)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'ordering': ['city'],
            },
        ),
    ]
