# Generated by Django 5.1.7 on 2025-04-04 23:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_tax',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
